version: '3.8'

services:
  web:
    build:
      context: .
    container_name: django-web
    volumes:
      - .:/app           # 挂载 Django 项目到容器
      - static_data:/usr/staticfiles/  # 挂载静态文件目录
    ports:
      - "8000:8000"      # 映射 Daphne 服务端口
    environment:
      - DJANGO_SETTINGS_MODULE=NCBCNet.settings
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"          # 映射 Nginx HTTP 端口
      - "443:443"        # 映射 Nginx HTTPS 端口
    depends_on:
      - web
    volumes:
      - ssl_data:/www/server/cert

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: {{ DB_ROOT_PASSWORD }}
      MYSQL_DATABASE: {{ SERVER_DB_NAME}}
      MYSQL_USER: {{ DB_USER_NAME}}
      MYSQL_PASSWORD: {{ DB_USER_PASSWORD }}
    ports:
      - "3306:3306"      # 映射数据库服务端口
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:                 # 使用数据卷持久化 MySQL 数据
  static_data:
  ssl_data: