version: '3.8'

services:
  web:
    build:
      context: .
    container_name: django-web
    volumes:
      - .:/app           # 挂载 Django 项目到容器
    ports:
      - "8000:8000"      # 映射 Daphne 服务端口
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"          # 映射 Nginx HTTP 端口
      - "443:443"        # 映射 Nginx HTTPS 端口
    depends_on:
      - web
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf  # 挂载自定义 Nginx 配置

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ;P7HRtH88Wn2tqCnwwES
      MYSQL_DATABASE: ncnetdb
      MYSQL_USER: ncnet
      MYSQL_PASSWORD: Ncbcnet@2024
    ports:
      - "3306:3306"      # 映射数据库服务端口
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:                 # 使用数据卷持久化 MySQL 数据