name: 功能请求
description: 提出一项新的功能。
title: （将此栏【替换】为你的标题）
labels: ["新功能", "待查看", "优先级：无"]
type: 特性
body:
  - type: markdown
    attributes:
      value: |
        感谢您贡献您的想法。
        请使用简洁明确的标题描述您希望增加或改进的功能。便于开发者了解您的想法。
  - type: textarea
    id: requested-feature
    attributes:
      label: 想要实现或优化的功能
    validations:
      required: true