[supervisord]
nodaemon=true

[program:daphne]
command=/app/venv/bin/daphne -e ssl:8000:privateKey=/usr/server/private.key:certKey=/usr/server/certificate.crt NCNBCNet.asgi:application
directory=/app
user=root
autostart=true
autorestart=true
stdout_logfile=/var/log/daphne_stdout.log
stderr_logfile=/var/log/daphne_stderr.log