# Generated by Django 6.0.2 on 2026-04-12 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_save', '0002_uploadedfile_file_size_uploadedfile_original_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='share',
            field=models.BooleanField(default=False),
        ),
    ]
