# Generated by Django 6.0.2 on 2026-08-22 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_save', '0003_uploadedfile_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='status',
            field=models.CharField(choices=[('processing', '处理中'), ('done', '完成'), ('failed', '失败')], default='done', max_length=20),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='thumbnails/'),
        ),
    ]
