name: Docker Image CI

on:
  push:
    branches: [ "Deploy" ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.12
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests
        run: |
          python manage.py test --settings=NCBCNet.test_settings
  build_and_push:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: login to ARC
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_NAME }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - uses: actions/checkout@v4
      - name: Set Tag Name
        id: get_tag
        run: echo "TAG=deploy-$(date +'%Y%m%d-%H%M%S')-${GITHUB_SHA:0:7}" >> $GITHUB_ENV
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ncnet:${TAG}
      - name: Save Docker image to tar
        run: docker save ncnet:${TAG} -o image.tar
      - name: Upload Docker image to release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: image.tar
          tag_name: ${{ env.TAG }}
          release_name: ${{ env.TAG }}
          draft: false
          prerelease: false
      - name: Build and push in ARC
        run: |
          docker build -t ${{ secrets.REGISTRY_NAME }}:${TAG} .
          docker push ${{ secrets.REGISTRY_NAME }}:${TAG}
