name: Docker Image CI

on:
  push:
    branches: [ "Deploy" ]
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag NCNet
    - name: Save Docker image to tar
      run: docker save NCNet -o image.tar
    - name: Upload Docker image to release
      uses: softprops/action-gh-release@v1
      with:
         files: image.tar
      env:
         GITHUB_TOKEN: ${ secrets.GITHUB_TOKEN }}



