name: Docker Image CI

on:
  push:
    branches: [ "Deploy" ]
  pull_request:
    branches: [ "Deploy" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Save Docker image to tar
      run: docker save my-app:${GITHUB_REF#refs/tags/} -o image.tar
    - name: Upload Docker image to release
      uses: softprops/action-gh-release@v1
      with:
         files: image.tar
      env:
         GITHUB_TOKEN: ${ secrets.GITHUB_TOKEN }}



