"""
Django settings for NCBCNet project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path
from datetime import datetime

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def env_bool(name, default=False):
    value = os.getenv(name)
    if value is None:
        return default
    return value.lower() in ('1', 'true', 'yes', 'on')


def env_list(name, default=''):
    value = os.getenv(name, default)
    return [item.strip() for item in value.split(',') if item.strip()]

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
secret_key_from_env = os.getenv('DJANGO_SECRET_KEY') or os.getenv('SECRET_KEY')
if secret_key_from_env:
    SECRET_KEY = secret_key_from_env
else:
    secret_file = Path(os.getenv('DJANGO_SECRET_FILE', BASE_DIR / 'SECRET'))
    if secret_file.exists():
        SECRET_KEY = secret_file.read_text(encoding='utf-8').strip()
    else:
        SECRET_KEY = 'django-insecure-dev-only-key-change-me'

# SECURITY WARNING: don't run with debug turned on in production!
APP_ENV = os.getenv('APP_ENV', 'development').lower()
DEBUG = env_bool('DEBUG', APP_ENV != 'production')
DAPHNEON_IN_DEBUG = env_bool('DAPHNEON_IN_DEBUG', DEBUG)
SQL_DEBUG = env_bool('SQL_DEBUG', False)
# 一定注意生产环境下将上面两个调为Flase！！！
'''
DEBUG Django 的默认调试选项
DAPHNEON_IN_DEBUG 这个选项用于是否启用daphne专属静态文件托管、媒体文件调试路径与调试数据库
SQL_DEBUG 是否在DEBUG下使用sql（WSL）
'''
ALLOWED_HOSTS = env_list('ALLOWED_HOSTS', '*')
# CSRF 可信来源：开发环境(DEBUG=True)默认信任 Vite 代理来源，免去手动配置；
# 生产(DEBUG=False)默认空，必须显式配置真实域名（https://你的域名）。
# 显式设置 CSRF_TRUSTED_ORIGINS 环境变量时始终以环境变量为准。
_default_csrf_origins = (
    'http://localhost:5173,http://127.0.0.1:5173,'
    'http://localhost:8000,http://127.0.0.1:8000'
) if DEBUG else ''
CSRF_TRUSTED_ORIGINS = env_list('CSRF_TRUSTED_ORIGINS', _default_csrf_origins)

# 生产环境关键配置校验：缺失/不安全时立即失败，避免带着开发默认值上线。
# 开发(DEBUG=True)跳过本校验，零配置即可运行。
if not DEBUG:
    from django.core.exceptions import ImproperlyConfigured
    if SECRET_KEY == 'django-insecure-dev-only-key-change-me':
        raise ImproperlyConfigured(
            '生产环境必须设置 DJANGO_SECRET_KEY（环境变量）或提供 SECRET 文件，'
            '不能使用开发默认密钥。'
        )
    if '*' in ALLOWED_HOSTS or not ALLOWED_HOSTS:
        raise ImproperlyConfigured(
            '生产环境必须显式设置 ALLOWED_HOSTS，不允许通配符 *。'
        )

# Security Settings
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

ENABLE_HTTPS_REDIRECT = env_bool('ENABLE_HTTPS_REDIRECT', not DEBUG)

CSRF_COOKIE_SECURE = env_bool('CSRF_COOKIE_SECURE', ENABLE_HTTPS_REDIRECT)

SESSION_COOKIE_SECURE = env_bool('SESSION_COOKIE_SECURE', ENABLE_HTTPS_REDIRECT)

SECURE_SSL_REDIRECT = ENABLE_HTTPS_REDIRECT

# HTTP Strict Transport Security (HSTS)
# Start with a low value in production and increase once verified.
SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '3600' if ENABLE_HTTPS_REDIRECT else '0'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool('SECURE_HSTS_INCLUDE_SUBDOMAINS', ENABLE_HTTPS_REDIRECT)
SECURE_HSTS_PRELOAD = env_bool('SECURE_HSTS_PRELOAD', ENABLE_HTTPS_REDIRECT)

# Application definition

INSTALLED_APPS = [
    "daphne",
    "rest_framework",
    'simpleui',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'server',
    'article',
    'study',
    'file_save',
    'usermanage',
    'taggit',
    'mptt',
    'django_ckeditor_5',
    # 'notifications',
    'mdeditor',
    'api',
]

# OpenAPI 文档（drf-spectacular，可选依赖；未安装时自动跳过）
try:
    import drf_spectacular  # noqa: F401
    INSTALLED_APPS.append('drf_spectacular')
except ImportError:
    pass

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'api.middleware.CookieAuthCsrfMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.csp.ContentSecurityPolicyMiddleware',
]

if DEBUG:
    INSTALLED_APPS.append("sslserver")
if DAPHNEON_IN_DEBUG:
    MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

ROOT_URLCONF = 'NCBCNet.urls'

# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'api.authentication.CookieJWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DATETIME_FORMAT': '%Y-%m-%d %H:%M:%S',
    'EXCEPTION_HANDLER': 'api.exceptions.custom_exception_handler',
    'DEFAULT_THROTTLE_RATES': {
        'login': '5/min',
        'register': '3/min',
        'upload': '30/min',
    },
}

# Simple JWT Configuration
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=2),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
}

# HttpOnly Cookie JWT 认证（ADR-003 中期方案）
# access/refresh token 存于 HttpOnly Cookie，前端 JS 无法读取，规避 XSS 窃取。
AUTH_COOKIE_ACCESS = 'nc_access'
AUTH_COOKIE_REFRESH = 'nc_refresh'
AUTH_COOKIE_SECURE = env_bool('AUTH_COOKIE_SECURE', ENABLE_HTTPS_REDIRECT)
AUTH_COOKIE_SAMESITE = os.getenv('AUTH_COOKIE_SAMESITE', 'Lax')
AUTH_COOKIE_PATH = '/'
# refresh Cookie 仅发送到认证相关端点，降低暴露面
AUTH_REFRESH_COOKIE_PATH = '/api/v1/auth/'

# 签名下载链接有效期（秒）
DOWNLOAD_LINK_TTL = int(os.getenv('DOWNLOAD_LINK_TTL', '300'))

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

customColorPalette = [
    {'color': 'hsl(4, 90%, 58%)', 'label': 'Red'},
    {'color': 'hsl(340, 82%, 52%)', 'label': 'Pink'},
    {'color': 'hsl(291, 64%, 42%)', 'label': 'Purple'},
    {'color': 'hsl(262, 52%, 47%)', 'label': 'Deep Purple'},
    {'color': 'hsl(231, 48%, 48%)', 'label': 'Indigo'},
    {'color': 'hsl(207, 90%, 54%)', 'label': 'Blue'},
]

CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': ['heading', '|', 'bold', 'italic', 'link',
                    'bulletedList', 'numberedList', 'blockQuote', 'imageUpload'],
    },
    'extends': {
        'blockToolbar': [
            'paragraph', 'heading1', 'heading2', 'heading3',
            '|',
            'bulletedList', 'numberedList',
            '|',
            'blockQuote',
        ],
        'toolbar': ['heading', '|', 'outdent', 'indent', '|', 'bold', 'italic', 'link', 'underline', 'strikethrough',
        'code','subscript', 'superscript', 'highlight', '|', 'codeBlock', 'sourceEditing', 'insertImage',
                    'bulletedList', 'numberedList', 'todoList', '|',  'blockQuote', 'imageUpload', '|',
                    'fontSize', 'fontFamily', 'fontColor', 'fontBackgroundColor', 'mediaEmbed', 'removeFormat',
                    'insertTable'],
        'image': {
            'toolbar': ['imageTextAlternative', '|', 'imageStyle:alignLeft',
                        'imageStyle:alignRight', 'imageStyle:alignCenter', 'imageStyle:side',  '|'],
            'styles': [
                'full',
                'side',
                'alignLeft',
                'alignRight',
                'alignCenter',
            ]
        },
        'table': {
            'contentToolbar': [ 'tableColumn', 'tableRow', 'mergeTableCells',
            'tableProperties', 'tableCellProperties' ],
            'tableProperties': {
                'borderColors': customColorPalette,
                'backgroundColors': customColorPalette
            },
            'tableCellProperties': {
                'borderColors': customColorPalette,
                'backgroundColors': customColorPalette
            }
        },
        'heading' : {
            'options': [
                { 'model': 'paragraph', 'title': 'Paragraph', 'class': 'ck-heading_paragraph' },
                { 'model': 'heading1', 'view': 'h1', 'title': 'Heading 1', 'class': 'ck-heading_heading1' },
                { 'model': 'heading2', 'view': 'h2', 'title': 'Heading 2', 'class': 'ck-heading_heading2' },
                { 'model': 'heading3', 'view': 'h3', 'title': 'Heading 3', 'class': 'ck-heading_heading3' }
            ]
        },
        'list': {
            'properties': {
                'styles': True,
                'startIndex': True,
                'reversed': True
            }
        }
    }
}

ASGI_APPLICATION = 'NCBCNet.asgi.application'

WSGI_APPLICATION = 'NCBCNet.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
# 生产环境使用MySQL数据库，开发环境使用SQLite数据库

db_engine = os.getenv('DB_ENGINE', 'sqlite' if DEBUG else 'mysql').lower()
if SQL_DEBUG or db_engine == 'mysql':
    default_db_host = '127.0.0.1' if DEBUG else 'db'
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.getenv('DB_NAME', 'ncnetdb'),
            'USER': os.getenv('DB_USER', 'ncnet'),
            'PASSWORD': os.getenv('DB_PASSWORD', 'dbuserpassword'),
            'HOST': os.getenv('DB_HOST', default_db_host),
            'PORT': os.getenv('DB_PORT', '3306'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.getenv('SQLITE_PATH', BASE_DIR / 'db.sqlite3'),
        }
    }
# 缓存配置：
# - 开发(DEBUG=True)且未显式指定 REDIS_URL：使用进程内缓存 LocMemCache，免装 Redis。
# - 生产(DEBUG=False)：默认 redis://redis:6379/1（Compose 服务名），或用 REDIS_URL 覆盖。
# - 任意环境显式设置 REDIS_URL 时，始终使用 Redis（如开发期要测试队列/共享缓存）。
_redis_url = os.getenv('REDIS_URL')
if DEBUG and not _redis_url:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "ncbcnet-dev-cache",
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": _redis_url or 'redis://redis:6379/1',
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
                # 如果 Redis 设置了密码，取消下面这行的注释
                # "PASSWORD": "你的密码",
            }
        }
    }
SESSION_ENGINE = os.getenv('SESSION_ENGINE', "django.contrib.sessions.backends.cache")
SESSION_CACHE_ALIAS = "default"

CONN_MAX_AGE = 60 * 60 * 1  # 数据库连接持续时间，单位为秒，这里设置为1小时

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

desktop_log_dir = "logs"
os.makedirs(desktop_log_dir, exist_ok=True)
logfile_name = f"debug_{datetime.now().strftime('%Y.%m.%d')}.log"
logfile_path = os.path.join(desktop_log_dir, logfile_name)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        # 生产日志写 stdout，由 Docker logging driver 收集（ARCHITECTURE_ROADMAP 6.7）
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
        # 仅 DEBUG 下写文件，生产不落容器内文件
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': logfile_path,
            'formatter': 'verbose',
            'filters': ['require_debug_true'],
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.request': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Chongqing'

USE_I18N = True

USE_TZ = True
SIMPLEUI_LOGO = "{% static 'server/favicon.ico' %}"
SIMPLEUI_HOME_INFO = False
SIMPLEUI_ANALYSIS = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
STATIC_ROOT = os.getenv('STATIC_ROOT', os.path.join(BASE_DIR, "staticfiles/"))
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static/'),  # 添加此项
]
MEDIA_URL = '/media/'
MEDIA_ROOT = os.getenv('MEDIA_ROOT', os.path.join(BASE_DIR, "mediafiles/"))
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
X_FRAME_OPTIONS = 'SAMEORIGIN'

# CORS：同源部署（Nginx 服务 SPA 并反代 /api），前端经 Vite 代理访问后端，
# 无跨域请求，故不引入 django-cors-headers；浏览器默认同源策略即为最安全的“白名单”。

# Content Security Policy（Django 5.1+/6.0 内建中间件，作用于 /admin 与旧模板页面；
# SPA 的 CSP 由 Nginx 下发，见 nginx/nginx.conf）。
SECURE_CSP = {
    "default-src": ("'self'",),
    "script-src": ("'self'", "'unsafe-inline'", "'unsafe-eval'"),
    "style-src": ("'self'", "'unsafe-inline'"),
    "img-src": ("'self'", "data:", "blob:"),
    "font-src": ("'self'", "data:"),
    "connect-src": ("'self'",),
    "frame-src": ("'self'",),
    "frame-ancestors": ("'self'",),
    "object-src": ("'none'",),
}

# OpenAPI 文档（drf-spectacular，可选依赖）
SPECTACULAR_SETTINGS = {
    'TITLE': 'NCBCNet API',
    'DESCRIPTION': '南城网前后端分离 REST API（/api/v1/）',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

# 对象存储（阶段三，S3 兼容：MinIO / 阿里云 OSS / 腾讯云 COS）。
# 未配置 OSS_ENDPOINT_URL 时使用本地磁盘存储，保证开发与现有部署不变。
DEFAULT_FILE_STORAGE = os.getenv(
    'DEFAULT_FILE_STORAGE',
    'django.core.files.storage.FileSystemStorage',
)
if os.getenv('OSS_ENDPOINT_URL'):
    DEFAULT_FILE_STORAGE = 'storages.backends.s3.S3Storage'
AWS_ACCESS_KEY_ID = os.getenv('OSS_ACCESS_KEY_ID', '')
AWS_SECRET_ACCESS_KEY = os.getenv('OSS_SECRET_ACCESS_KEY', '')
AWS_S3_ENDPOINT_URL = os.getenv('OSS_ENDPOINT_URL', '')
AWS_STORAGE_BUCKET_NAME = os.getenv('OSS_BUCKET', '')
AWS_QUERYSTRING_AUTH = env_bool('OSS_QUERYSTRING_AUTH', True)
AWS_S3_FILE_OVERWRITE = env_bool('OSS_FILE_OVERWRITE', False)
AWS_S3_OBJECT_PARAMETERS = {'CacheControl': 'max-age=86400'}